version: '3.8'

services:
  apiserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - ADK_CONFIG=/app/config.yaml
      - ADDR=:8080
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - adk-network

networks:
  adk-network:
    driver: bridge