# ADK NewAPI 模型池配置
plugin_dir: ./plugins
default_flow: novel_flow_v1
log_level: info

db:
  dsn: "postgres://user:pass@localhost:5432/adk?sslmode=disable"

queue:
  impl: redis
  addr: "redis://localhost:6379"
  stream: adk_tasks

# NewAPI 模型池配置
model_api_pools:
  # GLM-4.5 模型池 (通过NewAPI代理)
  glm_pool:
    base: "glm-4.5"  # 实际发送给NewAPI的模型名称
    endpoints:
      - url: "http://localhost:3000"
        apikey: "sk-xxx"

  # 测试池配置 (与测试代码保持一致)
  test_pool:
    base: "glm-4.5"
    endpoints:
      - url: "http://localhost:3000"
        apikey: "sk-xxx"

  # 多端点负载均衡示例
  glm_cluster:
    base: "glm-4.5"
    endpoints:
      - url: "http://localhost:3000"
        apikey: "sk-xxx"
      - url: "http://localhost:3001"  # 第二个NewAPI实例
        apikey: "sk-xxx"
      - url: "http://localhost:3002"  # 第三个NewAPI实例
        apikey: "sk-xxx"

  # 不同模型的配置示例
  gpt_pool:
    base: "gpt-3.5-turbo"  # 如果NewAPI代理了GPT模型
    endpoints:
      - url: "http://localhost:3000"
        apikey: "sk-xxx"

  claude_pool:
    base: "claude-3-sonnet"  # 如果NewAPI代理了Claude模型
    endpoints:
      - url: "http://localhost:3000"
        apikey: "sk-xxx"
